"""QLoRA and SFT hyperparameters — single source of truth for training."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from peft import LoraConfig


MODEL_ID = "Qwen/Qwen3-4B-Instruct-2507"
DRAFT_MODEL_ID = "Qwen/Qwen3-0.6B"
MAX_SEQ_LEN = 1536

# Dataset paths (generated by data/prepare.py)
TRAIN_DATA = "data/train.jsonl"
VAL_DATA = "data/val.jsonl"
OUTPUT_DIR = "adapter"
CHECKPOINT_DIR = "checkpoints"


@dataclass
class TrainingConfig:
    model_id: str = MODEL_ID
    max_seq_len: int = MAX_SEQ_LEN
    train_data: str = TRAIN_DATA
    val_data: str = VAL_DATA
    output_dir: str = OUTPUT_DIR
    checkpoint_dir: str = CHECKPOINT_DIR

    # QLoRA
    lora_r: int = 16
    lora_alpha: int = 32
    lora_dropout: float = 0.05
    lora_target_modules: list[str] = field(
        default_factory=lambda: ["q_proj", "k_proj", "v_proj", "o_proj"]
    )

    # SFT
    num_train_epochs: int = 1
    per_device_train_batch_size: int = 1
    gradient_accumulation_steps: int = 8
    learning_rate: float = 2e-4
    warmup_ratio: float = 0.03
    weight_decay: float = 0.01
    logging_steps: int = 10
    save_steps: int = 100
    # Mid-training eval OOMs on T4/P100 at max_seq_len=1536; use train/eval.py instead.
    eval_strategy: str = "no"
    eval_steps: int = 100
    bf16: bool = True
    gradient_checkpointing: bool = True

    def lora_config(self) -> LoraConfig:
        from peft import LoraConfig

        return LoraConfig(
            r=self.lora_r,
            lora_alpha=self.lora_alpha,
            lora_dropout=self.lora_dropout,
            target_modules=self.lora_target_modules,
            task_type="CAUSAL_LM",
        )
